controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

 
# Route par défaut redirigeant vers la page Department
index:
    path: /
    controller: 'App\Controller\DepartmentController::index'